resolver 127.0.0.11 valid=30s;

# API DEV
server {
    listen 80;
    server_name apidev.locacraft.fr;

    location / {
        set $upstream http://api-dev:8080;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Front DEV
server {
    listen 80;
    server_name dev.locacraft.fr;

    location / {
        set $upstream http://front-dev:80;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# API PROD
server {
    listen 80;
    server_name api.locacraft.fr;

    location / {
        set $upstream http://api-prod:8080;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Front PROD
server {
    listen 80;
    server_name app.locacraft.fr;

    location / {
        set $upstream http://front-prod:80;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
