// <auto-generated />
using System;
using LocaCraftAPI.LocaCraftAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocaCraftAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222103036_LeaseOnGoingBoolean")]
    partial class LeaseOnGoingBoolean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("LocaCraftAPI.Models.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOngoing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LessorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyCharges")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("TEXT");

                    b.Property<int>("RealEstateAssetId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("RentIndexReference")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LessorId");

                    b.HasIndex("RealEstateAssetId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.LeaseDocuments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DocumentContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId");

                    b.ToTable("LeaseDocuments");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.Lessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessors");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.RealEstateAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressComplement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RealEstateAssets");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaseId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.Lease", b =>
                {
                    b.HasOne("LocaCraftAPI.Models.Lessor", "Lessor")
                        .WithMany("Leases")
                        .HasForeignKey("LessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocaCraftAPI.Models.RealEstateAsset", "RealEstateAsset")
                        .WithMany("Leases")
                        .HasForeignKey("RealEstateAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lessor");

                    b.Navigation("RealEstateAsset");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.LeaseDocuments", b =>
                {
                    b.HasOne("LocaCraftAPI.Models.Lease", "Lease")
                        .WithMany("LeaseDocuments")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.Tenant", b =>
                {
                    b.HasOne("LocaCraftAPI.Models.Lease", "Lease")
                        .WithMany("Tenants")
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lease");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.Lease", b =>
                {
                    b.Navigation("LeaseDocuments");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.Lessor", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("LocaCraftAPI.Models.RealEstateAsset", b =>
                {
                    b.Navigation("Leases");
                });
#pragma warning restore 612, 618
        }
    }
}
