name: Deploy to VPS

on:
  push:
    tags:
      - 'push_api_dev_*'
      - 'push_api_prod_*'
      - 'push_front_dev_*'
      - 'push_front_prod_*'

jobs:
  deploy-api-dev:
    if: startsWith(github.ref_name, 'push_api_dev_')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API Dev
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/user/LocaCraftAPI
            git fetch origin
            git checkout dev_env
            git pull origin dev_env
            docker compose -f docker-compose.dev.yml up -d --build api

  deploy-api-prod:
    if: startsWith(github.ref_name, 'push_api_prod_')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy API Prod
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/user/LocaCraftAPI
            git fetch origin
            git checkout main
            git pull origin main
            docker compose -f docker-compose.prod.yml up -d --build api

  deploy-front-dev:
    if: startsWith(github.ref_name, 'push_front_dev_')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Front Dev
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/user/LocaCraftAPI
            git fetch origin
            git checkout dev_env
            git pull origin dev_env
            docker compose -f docker-compose.dev.yml up -d --build front

  deploy-front-prod:
    if: startsWith(github.ref_name, 'push_front_prod_')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Front Prod
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/user/LocaCraftAPI
            git fetch origin
            git checkout main
            git pull origin main
            docker compose -f docker-compose.prod.yml up -d --build front
